### ISSUE TITLE
Missing "dataloaders" attribute in datamodule

### ISSUE THREAD

**Issue by asiraudin** [cvignac/MiDi#5]
Hello Clément,

I'm trying to use your code for the QM9 dataset, but I have got this error :

``` 
                                                             ...
File "D:\Users\antoine\Documents\Sorbonne\Stage_PS\CTDGG\src\datasets\abstract_dataset.py", line 23, in __getitem__
    return self.dataloaders['train'][idx]
AttributeError: 'QM9DataModule' object has no attribute 'dataloaders'
```

It seems that the ```dataloaders``` attribute is not defined anywhere, hence raising an error when the Mixin ```__getitem__``` method is called. In Digress implementation, it was defined in the ```prepare_data``` method which is not present anymore in this implementation. How do you create this attribute now ?

Note that I'm not using ray, nor ray-lightning packages for now, could it interfer with the dataloader creation ?

Nice update of Digress code btw, it's nice that you added multi-gpu support !

Best regards,

Antoine

**Comment by cvignac** [comment]
Hello Antoine,
I have update the requirements yesterday, can you check that your current versions are correct?

If you still have issue you probably need to replace self.dataloaders['train'] by self.train_dataloader().

Things will change again soon, I will push multi-gpu support without ray before the end of the week.

**Comment by asiraudin** [comment]
Thanks for the quick reply !

The error came from the fact that I installed lightning v.2.0.3 before downgrading to 1.6.5, but didn't updated my imports accordingly (import syntax changed in lightning 2.0, I guess I was still running on 2.0.3).

I guess it's better if I stay in 1.6.5 and wait for multi-gpu support then !

**Comment by cvignac** [comment]
I just pushed it. Can you reinstall the environment and tell me if you experience some issues?

**Comment by asiraudin** [comment]
Dataloading seems to work fine with PL 2.0.4.

I'll probably try other functionalities of this repo in the coming weeks, I'll tell you if I face any other bug related to PL.

Best, 

Antoine
